version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["DataOntologyFunction=956068978982.dkr.ecr.ap-southeast-1.amazonaws.com/samapp7427b055/dataontologyfunction1a84606brepo"]

[default.global.parameters]
region = "ap-southeast-1"
